### PR TITLE
Wh

### PR DESCRIPTION
**Pull request by wesley-hughes**
# Description

Please include a summary of the changes and the related issue.

Fixes # (issue) 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How to Test?

Please describe the steps that you ran to verify your changes. Provide instructions so reviewer can follow those steps.

- [ created new post in client, added tags] 
- [ edited existing post, added tags, verified checkbox functioning for existing tags on post] 
- [ ]

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ericlfrey — APPROVED** [review]
Great work, team!

**Review by FreyaPotempa — APPROVED** [review]
Fetched and tested

**Review by macleann — APPROVED** [review]
Wow so good!

**Review by kristicornett — APPROVED** [review]
beautimus

**Pull request closed without merging**
