### PR TITLE
created some models

### PR DESCRIPTION
**Pull request by gonzalez-aj**
some models

### CODE REVIEW

**Review by wesley-hughes — APPROVED** [review]

**Review by ericlfrey — APPROVED** [review]
J'approve!

**Review by macleann — APPROVED** [review]
beautimus

**Review by kristicornett — COMMENTED** [review]
looks great

**Review by gonzalez-aj — COMMENTED** [review]
yay

**Comment by wesley-hughes** [comment]
cayoot

**Comment by macleann** [comment]
ttubs for lifee

**Pull request merged**
